version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-ecs: circleci/aws-ecs@0.0.6
jobs:
  build:
    docker:
    - image: fpco/stack-build:lts
    steps:
    - checkout
    - restore_cache:
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        name: Restore Cached Dependencies
        keys:
        - penrose-cache-{{ checksum "penrose.cabal" }}
    - run:
        name: Manually install Alex and Happy
        command: stack install alex happy
    - run:
        name: Resolve/Update Dependencies
        command: stack build
    - run:
        name: Run tests
        command: stack test
    - run:
        name: Install executable
        command: stack install
    - save_cache:
        name: Cache Dependencies
        key: penrose-cache-{{ checksum "penrose.cabal" }}
        paths:
        - ".stack"
        - ".stack-work"
        - "$HOME/.ghc"
        - "$HOME/.cabal"
        - "$HOME/.stack"

    - store_artifacts:
        # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
        path: ~/.local/bin/penrose
        destination: penrose-bin
    - persist_to_workspace:
        root: ~/.local/bin
        paths:
          - penrose

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
        requires: build
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: AWS_ACCESS_KEY
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        region: AWS_REGION
        repo: 114475215481.dkr.ecr.us-east-1.amazonaws.com/penrose
        dockerfile: Dockerfile
        attach-workspace: true
        workspace-root: ~/.local/bin
      - aws-ecs/deploy-service-update:
        requires: aws-ecr/build_and_push_image
        family: penrose-service
        cluster-name: arn:aws:eks:us-east-1:114475215481:cluster/penrose-cluster
        aws-access-key-id: AWS_ACCESS_KEY
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        aws-region: AWS_REGION

